export const CORE_OPTIONS = {
  Offensif: {
    primary: ['Additional Attack', 'Attack %'],
    defaultValues: {
      'Additional Attack': 5473,
      'Attack %': 53.44,
      'Critical Hit Damage': 6644,
      'Defense Penetration': 6644,
      'Damage Reduction': 6644,
      'Damage Increase': 6644,
      'Additional MP': 1170,
      'MP Recovery Rate Increase (%)': 5000,
      'MP Consumption Reduction': 1135,
      'Critical Rate': 6644,
    },
    secondary: [
      'Critical Hit Damage',
      'Defense Penetration',
      'Damage Reduction',
      'Damage Increase',
      'Additional MP',
      'MP Recovery Rate Increase (%)',
      'MP Consumption Reduction',
      'Critical Rate',
    ],
  },
  Défensif: {
    primary: ['Additional Defense', 'Defense %'],
    defaultValues: {
      'Additional Defense': 5473,
      'Defense %': 53.44,
      'Critical Hit Damage': 6644,
      'Defense Penetration': 6644,
      'Damage Reduction': 5000,
      'Damage Increase': 6644,
      'Additional MP': 1170,
      'MP Recovery Rate Increase (%)': 5000,
      'MP Consumption Reduction': 1135,
      'Critical Rate': 6644,
    },
    secondary: [
      'Critical Hit Damage',
      'Defense Penetration',
      'Damage Reduction',
      'Damage Increase',
      'Additional MP',
      'MP Recovery Rate Increase (%)',
      'MP Consumption Reduction',
      'Critical Rate',
    ],
  },
  Endurance: {
    primary: ['Additional HP', 'HP %'],
    defaultValues: {
      'Additional HP': 10946,
      'HP %': 53.44,
      'Critical Hit Damage': 6644,
      'Defense Penetration': 6644,
      'Damage Reduction': 5000,
      'Damage Increase': 6644,
      'Additional MP': 1170,
      'MP Recovery Rate Increase (%)': 5000,
      'MP Consumption Reduction': 1135,
      'Critical Rate': 6644,
    },
    secondary: [
      'Critical Hit Damage',
      'Defense Penetration',
      'Damage Reduction',
      'Damage Increase',
      'Additional MP',
      'MP Recovery Rate Increase (%)',
      'MP Consumption Reduction',
      'Critical Rate',
    ],
  },
};